<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="25323" started-at="2017-12-15T22:33:11Z" finished-at="2017-12-15T22:33:36Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="25323" started-at="2017-12-15T22:33:11Z" finished-at="2017-12-15T22:33:36Z">
      <class name="eComerceTests.UserSignUp">
        <test-method status="PASS" signature="setUp()[pri:0, instance:eComerceTests.UserSignUp@2bbf4b8b]" name="setUp" is-config="true" duration-ms="5" started-at="2017-12-15T14:33:11Z" finished-at="2017-12-15T14:33:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testTest()[pri:0, instance:eComerceTests.UserSignUp@2bbf4b8b]" name="testTest" duration-ms="13283" started-at="2017-12-15T14:33:11Z" finished-at="2017-12-15T14:33:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:eComerceTests.UserSignUp@2bbf4b8b]" name="setUp" is-config="true" duration-ms="0" started-at="2017-12-15T14:33:24Z" finished-at="2017-12-15T14:33:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validSignUpMainPageFull()[pri:0, instance:eComerceTests.UserSignUp@2bbf4b8b]" name="validSignUpMainPageFull" duration-ms="12000" started-at="2017-12-15T14:33:24Z" finished-at="2017-12-15T14:33:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Exception Thrown]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Exception Thrownat org.testng.Assert.fail(Assert.java:96)at eComerceTests.UserSignUp.validSignUpMainPageFull(UserSignUp.java:66)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validSignUpMainPageFull -->
      </class> <!-- eComerceTests.UserSignUp -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
